run_akinator: Akinator.exe
	Akinator.exe

Akinator.exe: Akinator_main.o Log_functions.o File_processing.o Stack_functions.o Akinator.h Stack\\Stack.h
	g++ -w Akinator_main.o Log_functions.o File_processing.o Stack_functions.o -o Akinator.exe

Stack_functions.o: Stack\\Stack_functions.cpp
	g++ -c -w Stack\\Stack_functions.cpp

Akinator_main.o: Akinator_main.cpp
	g++ -c -w Akinator_main.cpp

Log_functions.o: Log_functions.cpp 
	g++ -c -w Log_functions.cpp

File_processing.o: File_processing.cpp 
	g++ -c -w File_processing.cpp