run_akinator: Akinator.exe
	Akinator.exe

Akinator.exe: Akinator_main.o Log_functions.o File_processing.o Akinator.h
	g++ -w Akinator_main.o Log_functions.o File_processing.o -o Akinator.exe

 
Akinator_main.o: Akinator_main.cpp
	g++ -c -w Akinator_main.cpp

Log_functions.o: Log_functions.cpp 
	g++ -c -w Log_functions.cpp

File_processing.o: File_processing.cpp 
	g++ -c -w File_processing.cpp